name: 第一个 actions 示例

on: 
  push:
    branches:
      - master
    paths:
      - '**.*'

env:
  SERVER: production
  
  
defaults:
  runs-on: ubuntu-latest
  run:
    shell: bash
    working-directory: scripts
    
    
jobs:
  job1:
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
    
    
