name: 第一个 actions 示例

on: 
  push:
    branches:
      - master
    paths:
      - '**.*'

env:
  SERVER: production
  
  
defaults:
  run:
    shell: bash
    working-directory: ./
    
    
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - id: step1
        run: echo "::set-output name=test::$(node -pe \"require('./package.json').version\")"
      - id: step2
        run: echo "::set-output name=test::$(npm view chore-cli@latest version)"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
    
    
